# Tag identifying file association.
TAG: jeppebayer:EcoGenetics,population_genetics,vcf:workflowconfiguration
# The name of the relevant project account.
account: EcoGenetics
# Name of species being analyzed.
species_name: Entomobrya nicoleti
# Path to reference genome.
reference_genome_path: /faststorage/project/EcoGenetics/BACKUP/reference_genomes/Entomobrya_nicoleti/EG_EntNic_19022024_genome.fasta
# Directory for intermediary files.
working_directory_path: /faststorage/project/EcoGenetics/people/Jeppe_Bayer/population_genetics/steps/collembola
# Directory for final output files. (If left empty, output file will be placed within 'working_directory_path')
output_directory_path:
# Partition size of genome in base pairs
partition_size: 100000
# Freebayes settings
freebayes_settings:
  sample_ploidy: 100
  best_n_alleles: 3
  min_alternate_fraction: 0
  min_alternate_count: 2
# Filtering depths, the number included
filtering:
  minimum_depth: 300
  maximum_depth: 600
# Sample setup. List of dictionaries listing the configuration for each sample.
sample_list:
  -
    # Name of sample.
    sample_name: EntNic_aaRJ-C225
    # Name of sample group.
    sample_group: Grassland
    # Path to BAM file.
    bam_file: /faststorage/project/EcoGenetics/BACKUP/population_genetics/collembola/Entomobrya_nicoleti/EntNic_aaRJ-C225/EntNic_aaRJ-C225_filtered.bam
  -
    # Name of sample.
    sample_name: EntNic_aeRoe-C36
    # Name of sample group.
    sample_group: Grassland
    # Path to BAM file.
    bam_file: /faststorage/project/EcoGenetics/BACKUP/population_genetics/collembola/Entomobrya_nicoleti/EntNic_aeRoe-C36/EntNic_aeRoe-C36_filtered.bam
  -
    # Name of sample.
    sample_name: EntNic_BIJ-C30
    # Name of sample group.
    sample_group: Grassland
    # Path to BAM file.
    bam_file: /faststorage/project/EcoGenetics/BACKUP/population_genetics/collembola/Entomobrya_nicoleti/EntNic_BIJ-C30/EntNic_BIJ-C30_filtered.bam
  -
    # Name of sample.
    sample_name: EntNic_BJJ-C34
    # Name of sample group.
    sample_group: Grassland
    # Path to BAM file.
    bam_file: /faststorage/project/EcoGenetics/BACKUP/population_genetics/collembola/Entomobrya_nicoleti/EntNic_BJJ-C34/EntNic_BJJ-C34_filtered.bam
  -
    # Name of sample.
    sample_name: EntNic_BRS-C268
    # Name of sample group.
    sample_group: Grassland
    # Path to BAM file.
    bam_file: /faststorage/project/EcoGenetics/BACKUP/population_genetics/collembola/Entomobrya_nicoleti/EntNic_BRS-C268/EntNic_BRS-C268_filtered.bam
  -
    # Name of sample.
    sample_name: EntNic_DoeJ-C27
    # Name of sample group.
    sample_group: Grassland
    # Path to BAM file.
    bam_file: /faststorage/project/EcoGenetics/BACKUP/population_genetics/collembola/Entomobrya_nicoleti/EntNic_DoeJ-C27/EntNic_DoeJ-C27_filtered.bam
  -
    # Name of sample.
    sample_name: EntNic_DSJ-C190
    # Name of sample group.
    sample_group: Grassland
    # Path to BAM file.
    bam_file: /faststorage/project/EcoGenetics/BACKUP/population_genetics/collembola/Entomobrya_nicoleti/EntNic_DSJ-C190/EntNic_DSJ-C190_filtered.bam
  -
    # Name of sample.
    sample_name: EntNic_FHJ-C38
    # Name of sample group.
    sample_group: Grassland
    # Path to BAM file.
    bam_file: /faststorage/project/EcoGenetics/BACKUP/population_genetics/collembola/Entomobrya_nicoleti/EntNic_FHJ-C38/EntNic_FHJ-C38_filtered.bam
  -
    # Name of sample.
    sample_name: EntNic_FUR-C230
    # Name of sample group.
    sample_group: Grassland
    # Path to BAM file.
    bam_file: /faststorage/project/EcoGenetics/BACKUP/population_genetics/collembola/Entomobrya_nicoleti/EntNic_FUR-C230/EntNic_FUR-C230_filtered.bam    
  -
    # Name of sample.
    sample_name: EntNic_GEJ-C42
    # Name of sample group.
    sample_group: Grassland
    # Path to BAM file.
    bam_file: /faststorage/project/EcoGenetics/BACKUP/population_genetics/collembola/Entomobrya_nicoleti/EntNic_GEJ-C42/EntNic_GEJ-C42_filtered.bam
  -
    # Name of sample.
    sample_name: EntNic_GoeJ-C19
    # Name of sample group.
    sample_group: Grassland
    # Path to BAM file.
    bam_file: /faststorage/project/EcoGenetics/BACKUP/population_genetics/collembola/Entomobrya_nicoleti/EntNic_GoeJ-C19/EntNic_GoeJ-C19_filtered.bam
  -
    # Name of sample.
    sample_name: EntNic_GSJ-C274
    # Name of sample group.
    sample_group: Grassland
    # Path to BAM file.
    bam_file: /faststorage/project/EcoGenetics/BACKUP/population_genetics/collembola/Entomobrya_nicoleti/EntNic_GSJ-C274/EntNic_GSJ-C274_filtered.bam
  -
    # Name of sample.
    sample_name: EntNic_GUS-C41
    # Name of sample group.
    sample_group: Grassland
    # Path to BAM file.
    bam_file: /faststorage/project/EcoGenetics/BACKUP/population_genetics/collembola/Entomobrya_nicoleti/EntNic_GUS-C41/EntNic_GUS-C41_filtered.bam
  -
    # Name of sample.
    sample_name: EntNic_HHJ-C162
    # Name of sample group.
    sample_group: Grassland
    # Path to BAM file.
    bam_file: /faststorage/project/EcoGenetics/BACKUP/population_genetics/collembola/Entomobrya_nicoleti/EntNic_HHJ-C162/EntNic_HHJ-C162_filtered.bam
  -
    # Name of sample.
    sample_name: EntNic_JEJ-C119
    # Name of sample group.
    sample_group: Grassland
    # Path to BAM file.
    bam_file: /faststorage/project/EcoGenetics/BACKUP/population_genetics/collembola/Entomobrya_nicoleti/EntNic_JEJ-C119/EntNic_JEJ-C119_filtered.bam
  -
    # Name of sample.
    sample_name: EntNic_JHJ-C220
    # Name of sample group.
    sample_group: Grassland
    # Path to BAM file.
    bam_file: /faststorage/project/EcoGenetics/BACKUP/population_genetics/collembola/Entomobrya_nicoleti/EntNic_JHJ-C220/EntNic_JHJ-C220_filtered.bam
  -
    # Name of sample.
    sample_name: EntNic_JoeJ-C252
    # Name of sample group.
    sample_group: Grassland
    # Path to BAM file.
    bam_file: /faststorage/project/EcoGenetics/BACKUP/population_genetics/collembola/Entomobrya_nicoleti/EntNic_JoeJ-C252/EntNic_JoeJ-C252_filtered.bam
  -
    # Name of sample.
    sample_name: EntNic_KLJ-C127
    # Name of sample group.
    sample_group: Grassland
    # Path to BAM file.
    bam_file: /faststorage/project/EcoGenetics/BACKUP/population_genetics/collembola/Entomobrya_nicoleti/EntNic_KLJ-C127/EntNic_KLJ-C127_filtered.bam
  -
    # Name of sample.
    sample_name: EntNic_KoeJ-C212
    # Name of sample group.
    sample_group: Grassland
    # Path to BAM file.
    bam_file: /faststorage/project/EcoGenetics/BACKUP/population_genetics/collembola/Entomobrya_nicoleti/EntNic_KoeJ-C212/EntNic_KoeJ-C212_filtered.bam
  -
    # Name of sample.
    sample_name: EntNic_LEJ-C64
    # Name of sample group.
    sample_group: Grassland
    # Path to BAM file.
    bam_file: /faststorage/project/EcoGenetics/BACKUP/population_genetics/collembola/Entomobrya_nicoleti/EntNic_LEJ-C64/EntNic_LEJ-C64_filtered.bam
  -
    # Name of sample.
    sample_name: EntNic_LVJ-C76
    # Name of sample group.
    sample_group: Grassland
    # Path to BAM file.
    bam_file: /faststorage/project/EcoGenetics/BACKUP/population_genetics/collembola/Entomobrya_nicoleti/EntNic_LVJ-C76/EntNic_LVJ-C76_filtered.bam
  -
    # Name of sample.
    sample_name: EntNic_MSJ-C2
    # Name of sample group.
    sample_group: Grassland
    # Path to BAM file.
    bam_file: /faststorage/project/EcoGenetics/BACKUP/population_genetics/collembola/Entomobrya_nicoleti/EntNic_MSJ-C2/EntNic_MSJ-C2_filtered.bam
  -
    # Name of sample.
    sample_name: EntNic_NOJ-C37
    # Name of sample group.
    sample_group: Grassland
    # Path to BAM file.
    bam_file: /faststorage/project/EcoGenetics/BACKUP/population_genetics/collembola/Entomobrya_nicoleti/EntNic_NOJ-C37/EntNic_NOJ-C37_filtered.bam
  -
    # Name of sample.
    sample_name: EntNic_RYJ-C139
    # Name of sample group.
    sample_group: Grassland
    # Path to BAM file.
    bam_file: /faststorage/project/EcoGenetics/BACKUP/population_genetics/collembola/Entomobrya_nicoleti/EntNic_RYJ-C139/EntNic_RYJ-C139_filtered.bam
  -
    # Name of sample.
    sample_name: EntNic_SBJ-C52
    # Name of sample group.
    sample_group: Grassland
    # Path to BAM file.
    bam_file: /faststorage/project/EcoGenetics/BACKUP/population_genetics/collembola/Entomobrya_nicoleti/EntNic_SBJ-C52/EntNic_SBJ-C52_filtered.bam
  -
    # Name of sample.
    sample_name: EntNic_SHJ-C48
    # Name of sample group.
    sample_group: Grassland
    # Path to BAM file.
    bam_file: /faststorage/project/EcoGenetics/BACKUP/population_genetics/collembola/Entomobrya_nicoleti/EntNic_SHJ-C48/EntNic_SHJ-C48_filtered.bam
  -
    # Name of sample.
    sample_name: EntNic_SKJ-C16
    # Name of sample group.
    sample_group: Grassland
    # Path to BAM file.
    bam_file: /faststorage/project/EcoGenetics/BACKUP/population_genetics/collembola/Entomobrya_nicoleti/EntNic_SKJ-C16/EntNic_SKJ-C16_filtered.bam
  -
    # Name of sample.
    sample_name: EntNic_SKJ-C216
    # Name of sample group.
    sample_group: Grassland
    # Path to BAM file.
    bam_file: /faststorage/project/EcoGenetics/BACKUP/population_genetics/collembola/Entomobrya_nicoleti/EntNic_SKJ-C216/EntNic_SKJ-C216_filtered.bam
  -
    # Name of sample.
    sample_name: EntNic_STF-C266
    # Name of sample group.
    sample_group: Grassland
    # Path to BAM file.
    bam_file: /faststorage/project/EcoGenetics/BACKUP/population_genetics/collembola/Entomobrya_nicoleti/EntNic_STF-C266/EntNic_STF-C266_filtered.bam
  -
    # Name of sample.
    sample_name: EntNic_ULJ-C122
    # Name of sample group.
    sample_group: Grassland
    # Path to BAM file.
    bam_file: /faststorage/project/EcoGenetics/BACKUP/population_genetics/collembola/Entomobrya_nicoleti/EntNic_ULJ-C122/EntNic_ULJ-C122_filtered.bam
  -
    # Name of sample.
    sample_name: EntNic_ULJ-C60
    # Name of sample group.
    sample_group: Grassland
    # Path to BAM file.
    bam_file: /faststorage/project/EcoGenetics/BACKUP/population_genetics/collembola/Entomobrya_nicoleti/EntNic_ULJ-C60/EntNic_ULJ-C60_filtered.bam
  -
    # Name of sample.
    sample_name: EntNic_UTJ-C22
    # Name of sample group.
    sample_group: Grassland
    # Path to BAM file.
    bam_file: /faststorage/project/EcoGenetics/BACKUP/population_genetics/collembola/Entomobrya_nicoleti/EntNic_UTJ-C22/EntNic_UTJ-C22_filtered.bam
  -
    # Name of sample.
    sample_name: EntNic_VAJ-C24
    # Name of sample group.
    sample_group: Grassland
    # Path to BAM file.
    bam_file: /faststorage/project/EcoGenetics/BACKUP/population_genetics/collembola/Entomobrya_nicoleti/EntNic_VAJ-C24/EntNic_VAJ-C24_filtered.bam