# Tag identifying file association.
TAG: jeppebayer:EcoGenetics,population_genetics,freebayes:workflowconfiguration
# The name of the relevant project account.
account: EcoGenetics
# Name of species being analyzed.
species_name: Entomobrya nicoleti
# Path to reference genome.
reference_genome_path: /faststorage/project/EcoGenetics/BACKUP/reference_genomes/Entomobrya_nicoleti/EG_EntNic_19022024_genome.fasta
# Partition size of genome in base pairs
partition_size: 100000
# Sample setup. List of dictionaries listing the configuration for each sample.
sample_list:
  -
    # Name of sample.
    sample_name: EntNic_SKJ-C16
    # Name of sample group.
    sample_group: Grassland
    # Path to BAM file.
    bam_file: /faststorage/project/EcoGenetics/BACKUP/population_genetics/collembola/Entomobrya_nicoleti/EntNic_SKJ-C16/EntNic_SKJ-C16_filtered.bam
    # Directory for intermediary files.
    working_directory_path: /faststorage/project/EcoGenetics/people/Jeppe_Bayer/population_genetics/steps/collembola
    # Directory for final output files. (If left empty, output file will be placed within 'working_directory_path')
    output_directory_path:    
    # Freebayes settings
    freebayes_settings:
      sample_ploidy: 100
      best_n_alleles: 3
      min_alternate_fraction: 0
      min_alternate_count: 2
  -
    # Name of sample.
    sample_name: EntNic_SKJ-C216
    # Name of sample group.
    sample_group: Grassland
    # Path to BAM file.
    bam_file: /faststorage/project/EcoGenetics/BACKUP/population_genetics/collembola/Entomobrya_nicoleti/EntNic_SKJ-C216/EntNic_SKJ-C216_filtered.bam
    # Directory for intermediary files.
    working_directory_path: /faststorage/project/EcoGenetics/people/Jeppe_Bayer/population_genetics/steps/collembola
    # Directory for final output files. (If left empty, output file will be placed within 'working_directory_path')
    output_directory_path:
    # Freebayes settings
    freebayes_settings:
      sample_ploidy: 100
      best_n_alleles: 3
      min_alternate_fraction: 0
      min_alternate_count: 2
  -
    # Name of sample.
    sample_name: EntNic_STF-C266
    # Name of sample group.
    sample_group: Grassland
    # Path to BAM file.
    bam_file: /faststorage/project/EcoGenetics/BACKUP/population_genetics/collembola/Entomobrya_nicoleti/EntNic_STF-C266/EntNic_STF-C266_filtered.bam
    # Directory for intermediary files.
    working_directory_path: /faststorage/project/EcoGenetics/people/Jeppe_Bayer/population_genetics/steps/collembola
    # Directory for final output files. (If left empty, output file will be placed within 'working_directory_path')
    output_directory_path:
    # Freebayes settings
    freebayes_settings:
      sample_ploidy: 100
      best_n_alleles: 3
      min_alternate_fraction: 0
      min_alternate_count: 2
  -
    # Name of sample.
    sample_name: EntNic_ULJ-C122
    # Name of sample group.
    sample_group: Grassland
    # Path to BAM file.
    bam_file: /faststorage/project/EcoGenetics/BACKUP/population_genetics/collembola/Entomobrya_nicoleti/EntNic_ULJ-C122/EntNic_ULJ-C122_filtered.bam
    # Directory for intermediary files.
    working_directory_path: /faststorage/project/EcoGenetics/people/Jeppe_Bayer/population_genetics/steps/collembola
    # Directory for final output files. (If left empty, output file will be placed within 'working_directory_path')
    output_directory_path:
    # Freebayes settings
    freebayes_settings:
      sample_ploidy: 100
      best_n_alleles: 3
      min_alternate_fraction: 0
      min_alternate_count: 2
  -
    # Name of sample.
    sample_name: EntNic_ULJ-C60
    # Name of sample group.
    sample_group: Grassland
    # Path to BAM file.
    bam_file: /faststorage/project/EcoGenetics/BACKUP/population_genetics/collembola/Entomobrya_nicoleti/EntNic_ULJ-C60/EntNic_ULJ-C60_filtered.bam
    # Directory for intermediary files.
    working_directory_path: /faststorage/project/EcoGenetics/people/Jeppe_Bayer/population_genetics/steps/collembola
    # Directory for final output files. (If left empty, output file will be placed within 'working_directory_path')
    output_directory_path:
    # Freebayes settings
    freebayes_settings:
      sample_ploidy: 100
      best_n_alleles: 3
      min_alternate_fraction: 0
      min_alternate_count: 2
  -
    # Name of sample.
    sample_name: EntNic_UTJ-C22
    # Name of sample group.
    sample_group: Grassland
    # Path to BAM file.
    bam_file: /faststorage/project/EcoGenetics/BACKUP/population_genetics/collembola/Entomobrya_nicoleti/EntNic_UTJ-C22/EntNic_UTJ-C22_filtered.bam
    # Directory for intermediary files.
    working_directory_path: /faststorage/project/EcoGenetics/people/Jeppe_Bayer/population_genetics/steps/collembola
    # Directory for final output files. (If left empty, output file will be placed within 'working_directory_path')
    output_directory_path:
    # Freebayes settings
    freebayes_settings:
      sample_ploidy: 100
      best_n_alleles: 3
      min_alternate_fraction: 0
      min_alternate_count: 2
  -
    # Name of sample.
    sample_name: EntNic_VAJ-C24
    # Name of sample group.
    sample_group: Grassland
    # Path to BAM file.
    bam_file: /faststorage/project/EcoGenetics/BACKUP/population_genetics/collembola/Entomobrya_nicoleti/EntNic_VAJ-C24/EntNic_VAJ-C24_filtered.bam
    # Directory for intermediary files.
    working_directory_path: /faststorage/project/EcoGenetics/people/Jeppe_Bayer/population_genetics/steps/collembola
    # Directory for final output files. (If left empty, output file will be placed within 'working_directory_path')
    output_directory_path:
    # Freebayes settings
    freebayes_settings:
      sample_ploidy: 100
      best_n_alleles: 3
      min_alternate_fraction: 0
      min_alternate_count: 2