# (str). The name of the relevant project account.
account: EcoGenetics
# (str). Conda environment for assembly (gwf, pyyaml, bedtools, bcftools, matplotlib, pandas).
condaEnvironment01: popgen
# (str). Name of species being analyzed
speciesName: Isotoma viridis
# (str.) Taxonomic group. Can be left empty.
taxonomicGroup: Collembola
# (str). Directory for intermediate files.
workingDirectoryPath: /faststorage/project/EcoGenetics/people/Jeppe_Bayer/population_genetics/steps
# (str). Directory for final output files. Can be left empty (If left empty, output file will be placed within 'working_directory_path').
outputDirectoryPath: 
# (str). Path to BED file of intergenic regions.
intergenicBed: /faststorage/project/EcoGenetics/BACKUP/population_genetics/reference_genomes/collembola/Isotoma_viridis/annotation/EG_IsoVir_23082024_genomic.intergenic.bed
# (str). Path to BED file of repetitive regions.
repeatsBed: /faststorage/project/EcoGenetics/BACKUP/population_genetics/reference_genomes/collembola/Isotoma_viridis/annotation/EG_IsoVir_23082024_genomic.repeats.bed
# (list). List of paths to VCF files.
vcfFiles:
  - /faststorage/project/EcoGenetics/general_workflow_outputs/population_genetics/vcf/collembola/Isotoma_viridis/grassland/IsoVir.grassland.ingroup.allQuality.freebayes.merge.normalized.filtered_DP200-798.vcf.gz
  - /faststorage/project/EcoGenetics/general_workflow_outputs/population_genetics/vcf/collembola/Isotoma_viridis/grassland/IsoVir.grassland.ingroup.highQuality.freebayes.merge.normalized.filtered_DP200-802.vcf.gz
  - /faststorage/project/EcoGenetics/general_workflow_outputs/population_genetics/vcf/collembola/Isotoma_viridis/conventional_agriculture/IsoVir.conventional_agriculture.ingroup.allQuality.freebayes.merge.normalized.filtered_DP200-780.vcf.gz
  - /faststorage/project/EcoGenetics/general_workflow_outputs/population_genetics/vcf/collembola/Isotoma_viridis/conservation_agriculture/IsoVir.conservation_agriculture.ingroup.allQuality.freebayes.merge.normalized.filtered_DP200-572.vcf.gz