# (str). The name of the relevant project account.
account: 
# (str).Name of species being analyzed
speciesName: 
# (str). Directory for intermediary files.
workingDirectoryPath: 
# (str). Directory for final output files.
outputDirectoryPath: 
# (str).
outgroupVcfFile:
# (list).
vcfGroupList:
  -
    # (str).
    groupName:
    # (str). 
    vcfFile:
    # (int). 
    minimunCoverage:
    # (int).
    maximumCoverage:
    # (str).
    withinThresholdBedFile: