# Tag identifying file association.
TAG: jeppebayer:EcoGenetics,population_genetics,alignment,depth:workflowconfiguration
# (str). The name of the relevant project account.
account: 
# (str). Taxonomic group. Can be left empty.
taxonomicGroup: 
# (str). Name of species being analyzed.
speciesName: 
# (str). Directory for intermediary files.
workingDirectoryPath: 
# (str). Directory for final output files. (If left empty, output file will be placed within 'workingDirectoryPath').
outputDirectoryPath: 
# (int). A lower coverage threshold for the identification of a coverage distribution peak.
lowerCoverageThreshold: 
# (list). Sample setup. List of dictionaries listing the configuration for each sample.
sampleList:
  - 
    # (str). Name of sample group.
    groupName: 
    # (list). List of paths to BAM files.
    bamFileList:
      - 