# Tag identifying file association.
TAG: jeppebayer:EcoGenetics,population_genetics,genetic_load:workflowconfiguration
# The name of the relevant project account.
account: EcoGenetics
# Name of species being analyzed
species_name: Isotoma viridis
# Path to reference genome file.
reference_genome_file: /faststorage/project/EcoGenetics/BACKUP/reference_genomes/Isotoma_viridis/EG_IsoVir_19022024_genomic.fasta
# Path to reference annotation file in GTF format.
gtf_annotation_file: /faststorage/project/EcoGenetics/BACKUP/reference_genomes/Isotoma_viridis/annotation/EG_IsoVir_19022024_genomic.gtf
# Directory for intermediary files.
working_directory_path: /faststorage/project/EcoGenetics/people/Jeppe_Bayer/population_genetics/steps/collembola
# Directory for final output files. (If left empty, output file will be placed within 'working_directory_path')
output_directory_path:
# SNPGenie settings.
snpgenie_settings:
  # Minimum SNP frequency to include (proportion)(default 0).
  minfreq: 0
  # Length of the (optional) sliding (codon) window used in analysis (default 9)
  slidingwindow: 9
# Sample setup. List of dictionaries listing the configuration for each sample.
sample_list:
  -
    # Name of sample.
    sample_name: IsoVir_all
    # Name of sample group.
    sample_group: All
    # Path to VCF file.
    vcf_file: /faststorage/project/EcoGenetics/BACKUP/population_genetics/collembola/Isotoma_viridis/IsoVir/vcf_allsites_maxcov0.98_mincov2_mincnt2_minfrq0_missfrc0.001_bq15/IsoVir.allsites_maxcov0.98_mincov2_mincnt2_minfrq0_missfrc0.001_bq15.biallelic.vcf.gz
    # Path to BAM file.
    bam_file: /faststorage/project/EcoGenetics/BACKUP/population_genetics/collembola/Isotoma_viridis/IsoVir_BJJ-C98/IsoVir_BJJ-C98_filtered.bam