# The name of the relevant project account.
account: EcoGenetics
# Name of species being analyzed
species_name: Isotoma viridis
# Path to VCF file (can be .gz compressed).
vcf_file: /faststorage/project/EcoGenetics/BACKUP/population_genetics/collembola/Isotoma_viridis/IsoVir/vcf_allsites_maxcov0.98_mincov2_mincnt2_minfrq0_missfrc0.001_bq15/IsoVir.allsites_maxcov0.98_mincov2_mincnt2_minfrq0_missfrc0.001_bq15.vcf.gz
# Path to reference genome file.
reference_genome_path: /faststorage/project/EcoGenetics/BACKUP/reference_genomes/Isotoma_viridis/EG_IsoVir_19022024_genomic.fasta
# Path to reference annotation file in GTF format.
gtf_annotation_file: /faststorage/project/EcoGenetics/BACKUP/reference_genomes/Isotoma_viridis/annotation/EG_IsoVir_19022024_genomic.gtf
# Directory for intermediary files.
working_directory_path: /faststorage/project/EcoGenetics/people/Jeppe_Bayer/population_genetics/steps/collembola
# Directory for final output files.
output_directory_path: 
