# Tag identifying file association.
TAG: jeppebayer:EcoGenetics,population_genetics,vcf:workflowconfiguration
# The name of the relevant project account.
account: EcoGenetics
# Name of species being analyzed.
species_name: Entomobrya nivalis
# Path to reference genome.
reference_genome_path: /faststorage/project/EcoGenetics/BACKUP/reference_genomes/Entomobrya_nicoleti/EG_EntNic_19022024_genome.fasta
# Directory for intermediary files.
working_directory_path: /faststorage/project/EcoGenetics/people/Jeppe_Bayer/population_genetics/steps/collembola
# Directory for final output files. (If left empty, output file will be placed within 'working_directory_path')
output_directory_path:
# Partition size of genome in base pairs
partition_size: 100000
# Freebayes settings
freebayes_settings:
  sample_ploidy: 100
  best_n_alleles: 3
  min_alternate_fraction: 0
  min_alternate_count: 2
# Filtering depths, the number included
filtering:
  minimum_depth: 300
  maximum_depth: 600
# Sample setup. List of dictionaries listing the configuration for each sample.
sample_list:
  -
    # Name of sample.
    sample_name: EntNiv_MSJ-C93
    # Name of sample group.
    sample_group: E_nivalis_x_E_nicoleti
    # Path to BAM file.
    bam_file: /faststorage/project/EcoGenetics/people/Jeppe_Bayer/population_genetics/steps/collembola/Entomobrya_nivalis/mapping/e_nivalis_x_e_nicoleti/filtered_alignment/EntNiv_MSJ-C93/EntNiv_MSJ-C93.filtered.bam