# Tag identifying file association.
TAG: jeppebayer:EcoGenetics,population_genetics,mapping:workflowconfiguration
# The name of the relevant project account.
account: 
# Taxonomic group
taxonomic_group: 
# Name of species being analyzed
species_name: 
# Path to reference genome file in FASTA format
reference_genome_path: 
# Directory for intermediary files.
working_directory_path: 
# # Directory for final output files. (If left empty, output file will be placed within 'working_directory_path')
output_directory_path: 
# AdapterRemoval settings.
adapterremoval_settings:
  min_quality: 25
  min_length: 20
  adaptersequence1: AAGTCGGAGGCCAAGCGGTCTTAGGAAGACAA
  adaptersequence2: AAGTCGGATCGTAGCCATGTCGTTCTGTGAGCCAAGGAGTTG
# Samtools filter settings.
filter_settings:
  flags_excluded: 3844
  flags_required: 
  min_mq: 20
# List of path to sample folders containing resequencing data.
sample_lists:
  -
    group_name: 
    sample_folder_list:
      - 
  -
    group_name: 
    sample_folder_list:
      - 
